### ISSUE TITLE
about apple music

### ISSUE THREAD

**Issue by baba990aini** [GeorgeGorbanev/streamnx#1]
I am using Apple Music, how can I set it up to access the corresponding music resources and streaming media

**Comment by GeorgeGorbanev** [comment]
Hi, @baba990aini!

> streaming media

Actually, for now Apple Music not providing methods to access streaming media. We can't play music any other way than using official Apple applications 😔

> I am using Apple Music, how can I set it up to access the corresponding music resources

The goal of this package is to access multiple streaming platforms with universal API, that is why default way to set up this package requires to configure Spotify and Youtube to run, as described [in README](https://github.com/GeorgeGorbanev/streamnx?tab=readme-ov-file#configuration)

However, if you you want to use this package only for Apple Music and don't want to setup everything else, you can implement "dummy" adapter for providers you don't want to use and put it to constructor options:

1) Implement dummy adapter:
``` golang
type DummyAdapter struct{}

func (d *DummyAdapter) FetchTrack(ctx context.Context, id string) (*streamnx.Entity, error) {
	return nil, fmt.Errorf("not implemented")
}

func (d *DummyAdapter) SearchTrack(ctx context.Context, artistName, trackName string) (*streamnx.Entity, error) {
	return nil, fmt.Errorf("not implemented")
}

func (d *DummyAdapter) FetchAlbum(ctx context.Context, id string) (*streamnx.Entity, error) {
	return nil, fmt.Errorf("not implemented")
}

func (d *DummyAdapter) SearchAlbum(ctx context.Context, artistName, albumName string) (*streamnx.Entity, error) {
	return nil, fmt.Errorf("not implemented")
}
```
2) Implement dummy translator:

``` golang

type DummyTranslator struct{}

func (d *DummyTranslator) TranslateEnToRu(context.Context, string) (string, error) {
	return "", fmt.Errorf("not implemented")
}

func (d *DummyTranslator) Close() error {
	return nil
}
```

3) Put them to constructor as options:
``` golang
         registry, err := streamnx.NewRegistry(
		context.Background(),
		streamnx.Credentials{},
		streamnx.WithProviderAdapter(streamnx.Spotify, &DummyAdapter{}),
		streamnx.WithProviderAdapter(streamnx.Youtube, &DummyAdapter{}),
		streamnx.WithTranslator(&DummyTranslator{}),
	)
	if err != nil {
		panic(err)
	}
```
4) Use registry object to access tracks or albums:

``` golang

	link, err := streamnx.ParseLink("https://music.apple.com/us/album/never-gonna-give-you-up/1559885420?i=1559885421")
	if err != nil {
		panic(err)
	}

	trackByID, err := registry.Fetch(context.Background(), link.Provider, link.EntityType, link.EntityID)
	if err != nil {
		panic(err)
	}

	trackByName, err := registry.Search(context.Background(), streamnx.Track, "Rick Astley", "Never Gonna Give You Up")
	if err != nil {
		panic(err)
	}
```
